# Generated by Django 3.2.6 on 2022-08-11 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguage',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_lang_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('setting_key', models.CharField(choices=[('APP_TITLE', 'Application Title'), ('PRIMARY_LOGO_URL', 'Primary Logo URL'), ('APP_SLOGAN', 'Application Slogan'), ('COPYRIGHT_STRING', 'Copyright Text')], default='APP_TITLE', max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.supportedlanguage')),
            ],
            options={
                'abstract': False,
                'unique_together': {('id', 'language')},
            },
        ),
    ]
