# Generated by Django 3.2.6 on 2022-08-11 22:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220811_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationSettings',
            new_name='ApplicationSetting',
        ),
    ]
