# Generated by Django 3.2.6 on 2022-08-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supportedlanguage_languagekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsetting',
            name='setting_value',
            field=models.TextField(blank=True),
        ),
    ]
