# Generated by Django 3.2.6 on 2022-08-17 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_applicationsetting_setting_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postalcode', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('companyName', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='settings/flags')),
                ('billing_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_tenant', to='core.address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_tenant', to='core.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
