# Generated by Django 3.2.6 on 2022-08-18 16:33

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_address_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postalcode', models.CharField(blank=True, max_length=7)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('aboutme', ckeditor.fields.RichTextField(blank=True)),
                ('profilePicture', models.ImageField(blank=True, default='', null=True, upload_to=core.models.TenantUser.upload_profile_file_name)),
                ('notes', models.TextField(blank=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenantuser_address', to='core.address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.supportedlanguage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='core.tenant')),
                ('userObject', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
