# Generated by Django 3.2.6 on 2022-08-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_tenant', to='core.address'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_tenant', to='core.address'),
        ),
    ]
